repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
    -   id: check-added-large-files
    -   id: debug-statements
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff
        args:
        - --fix
        - --exit-non-zero-on-fix